config/routes.rb
HarvesterNg::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :departments, only: [:index, :show] do
    resources :groups, only: [:edit, :update, :index] do
      post :get_next, on: :collection
      get :autocomplete_audience_name, on: :collection
      get :autocomplete_need_name, on: :collection
    end

    resources :needs, only: [:edit, :update, :index] do
      post :get_next, on: :collection
      get :autocomplete_audience_name, on: :collection
      get :autocomplete_need_name, on: :collection
      get :autocomplete_new_page_uri, on: :collection
    end
  end

  resource :export, only: [:show] do
    post :to_gdocs
    get 'ping(/:exported_data_id)', action: :ping, as: :ping
  end

  devise_for :users

  match '/' => redirect('/departments')

end

app/models/need.rb
class Need < ActiveRecord::Base
  include TakableMixin

  attr_accessible :name
  has_and_belongs_to_many :pages, join_table: :pages_needs

  validates_presence_of :name
  validates_uniqueness_of :name

  before_save do
    self.done = _done?
    true
  end

  # Override TakableMixin

  def users_who_can_take_me
    User.find_by_sql(['select distinct users.* from users, users_departments, groups, pages, pages_needs where users.id = users_departments.user_id and groups.department_id = users_departments.department_id and groups.id = pages.group_id and pages.id = pages_needs.page_id and pages_needs.need_id = ?', self.id])
  end

  def _done?
    pages.all? do |p|
      !p.new_pages.empty?
    end
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  autocomplete :audience, :name, full: true
  autocomplete :need, :name, full: true
  autocomplete :new_page, :uri, full: true

  takable_resource :need
  def resource_name
    :need
  end

  def update_page page, formdata
    page.needs << @resource

    formdata[:new_pages].split(',').map{|s|s.strip}.each do |new_page|
      np = NewPage.find_by_uri(new_page)
      if np
        page.new_pages << np
      else
        page.new_pages.create!(uri: new_page)
      end
    end
  end

  def department_and_need_match
    unless @department.needs.include? @need
      redirect_to department_needs_path
    end
  end

  ###

  def edit
    @need = Need.find(params[:id])
    department_and_need_match

    unless current_user.can_edit_department? @department
      redirect_to department_needs_path
    end
  end

  def index
    @needs = @department.needs
  end
end

app/views/needs/edit.html.haml
= form_tag({action: :update, id: @need.id}, method: :put) do
  .row-fluid
    .span8
      %h1= @need.name
    .span4.button-area
      = buttons_for @need

  .row-fluid
    #need.span12
      %table.table.table-striped.table-condensed.table-bordered
        %thead
          %tr
            %th Original URL
            %th Propositions
            %th Other needs
            %th Audiences
            %th New URLs
        %tbody
          - @need.pages.each do |page|
            %tr
              %td.page
                %a{:href => page.uri, :target => '_blank'}=page.name
              %td.propositions
                - taxonomy_tag(:attrs)[:cls].all.each_with_index do |a, i|
                  %label{class: "proposition_#{i}"}
                    = check_box_tag("pages[#{page.id}][attrs][#{a.name}]", '1', page.has_tag?(:attrs, a.name), {disabled: !@need.taken_by?(current_user)})
                    = a.name
              %td.needs
                = autocomplete_field_tag("pages[#{page.id}][needs]", page.needs.select{|n|n != @need}.map{|n| n.name}.join(','), autocomplete_need_name_department_needs_path, {placeholder: "Add...", class: "editable_list", data: {for: "needs_#{page.id}"}, disabled: !@need.taken_by?(current_user)})
              %td.audiences
                = autocomplete_field_tag("pages[#{page.id}][audiences]", page.audiences.map{|a| a.name}.join(','), autocomplete_audience_name_department_needs_path, {placeholder: "Add...", class: "editable_list", data: {for: "audiences_#{page.id}"}, disabled: !@need.taken_by?(current_user)})
              %td.new_pages
                = autocomplete_field_tag("pages[#{page.id}][new_pages]", page.new_pages.map{|p| p.uri}.join(','), autocomplete_new_page_uri_department_needs_path, {placeholder: "Add...", class: "editable_list", data: {for: "new_pages_#{page.id}"}, disabled: !@need.taken_by?(current_user)})

  .row-fluid
    .span8
      &nbsp;
    .span4.button-area
      = buttons_for @need

app/views/needs/index.html.haml
.row-fluid
  %h2 #{@department.name}: Needs

  = form_tag({action: :get_next}, method: :post) do
    =submit_tag('Get a need', class: 'btn')

  %table.table.table-striped.table-condensed.table-bordered
    - @needs.each do |need|
      %tr
        %td.number.small
          = need.pages.length
          %span{class: need.done? ? 'icon-ok' : 'icon-remove'}
        %td=link_to(need.name, edit_department_need_path(@department, need))
  %ul