config/routes.rb
HarvesterNg::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :departments, only: [:index, :show] do
    resources :groups, only: [:edit, :update, :index] do
      post :get_next, on: :collection
      get :autocomplete_audience_name, on: :collection
      get :autocomplete_need_name, on: :collection
    end

    resources :needs, only: [:edit, :update, :index] do
      post :get_next, on: :collection
      get :autocomplete_audience_name, on: :collection
      get :autocomplete_need_name, on: :collection
      get :autocomplete_new_page_uri, on: :collection
    end
  end

  resource :export, only: [:show] do
    post :to_gdocs
    get 'ping(/:exported_data_id)', action: :ping, as: :ping
  end

  devise_for :users

  match '/' => redirect('/departments')

end

app/models/group.rb
class Group < ActiveRecord::Base
  include TakableMixin

  attr_accessible :name
  belongs_to :department
  has_many :pages
  belongs_to :user, :foreign_key => 'taken_by'

  before_save do
    self.done = _done?
    true
  end

  # Override TakableMixin

  def users_who_can_take_me
    department.users
  end

  def _done?
    pages.all? do |page|
      page.done?
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  autocomplete :audience, :name, full: true
  autocomplete :need, :name, full: true

  takable_resource :group
  def resource_name
    :group
  end

  ###

  def index
    @groups = @department.groups
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def edit
    @group = Group.find(params[:id])

    unless current_user.can_edit_department? @department
      redirect_to department_groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def taxonomy_tag tax
    taxonomies[tax]
  end

  def taxonomies
    HarvesterNg::Application.config.taxonomies
  end

  def taxonomies_a
    taxonomies.keys
  end
end

app/views/groups/edit.html.haml
= form_tag({action: :update, id: @group.id}, method: :put, class: :main) do
  .row-fluid
    .span12
      %h1= @group.name
  .row-fluid
    .span2
      %p.count=pluralize(@group.pages.size, 'page')

      = buttons_for @group

    #group.span10
      .table-container.table-bordered
        %table.table.table-striped.table-condensed
          %thead
            %tr
              %th Original URL
              %th
                %table.attributes
                  %tr
                    - Attr.all.each do |a|
                      %td{:class => a.name}
                        %abbr{:title=> a.description}=a.name
              %th Citizen or business need
              %th Specialist audience or subject
            %tr
              %th
              - taxonomies_a.each do |tax|
                - tag = taxonomy_tag(tax)
                %th
                  - case tag[:type]
                  - when :checkboxes
                    %table.attributes.meta
                      %tr
                        - tag[:cls].all.each do |a|
                          %td{:class => a.name}
                            %input{type: 'checkbox', data: {name: "#{tax}::#{a.name}"}, disabled: !@group.taken_by?(current_user)}

          %tbody
            - counter = 0
            - @group.pages.each do |page|
              - if (counter+=1) % 5 == 0
                - counter = 0
                %tr
                  %td
                  %th
                    %table.attributes
                      %tr
                        - Attr.all.each do |a|
                          %td{:class => a.name}
                            %abbr{:title=> a.description}=a.name
                  %td
                  %td
              %tr
                %td
                  %a{href: page.uri, target: 'content'}= page.name
                - taxonomies_a.each do |tax|
                  - tag = taxonomy_tag(tax)
                  %td
                    - case tag[:type]
                    - when :checkboxes
                      %table.attributes.body
                        %tr
                          - tag[:cls].all.each do |a|
                            %td{:class => a.name}= check_box_tag('pages[%s][%s][%s]' % [page.id, tax, a.name], '1', page.has_tag?(tax, a.name), {data: {name: "#{tax}::#{a.name}"}, disabled: !@group.taken_by?(current_user)})
                    - when :text
                      = autocomplete_field_tag('pages[%s][%s]' % [page.id, tax], page.tags(tax).join(', '), send("autocomplete_#{tax.to_s[0..-2]}_name_department_groups_path"), {disabled: !@group.taken_by?(current_user), class: 'editable_list', data: {delimiter: ', '}})

.row-fluid
  %iframe.span12{name: :content, id: :content}

app/views/groups/index.html.haml
.row-fluid
  %h2 #{@department.name}: Groups 
  %p.meta
    #{@department.percentage_groups_done}% complete

  = form_tag({action: :get_next}, method: :post) do
    =submit_tag('Get a group', class: 'btn')

  %table.table.table-striped.table-condensed.table-bordered
    %tr
      %th Count
      %th Group
      %th Taken by

    - @groups.each do |group|
      %tr
        %td.number.small
          = group.pages.length
          %span{class: group.done? ? 'icon-ok' : 'icon-remove'}
        %td= link_to(group.name, edit_department_group_path(@department.id, group))
        %td=group.user.email if !group.user.blank?